development:
  adapter: postgresql
  encoding: unicode
  database: sabz_account_development
  pool: 5
  username: arashbm

test:
  adapter: postgresql
  encoding: unicode
  database: sabz_account_test
  pool: 5
  username: arashbm

production:
  adapter: postgresql
  encoding: unicode
  database: sabz_account_production
  pool: 5
  username: arashbm
